---
- name: Create nginx drop-in configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: "0755"
  with_items:
    - "{{ nginx.prefix.config }}/include"
    - "{{ nginx.prefix.config }}/http.d"
    - "{{ nginx.prefix.config }}/stream.d"

- name: Template nginx configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    mode: "0644"
  loop:
    - src: nginx.conf
      dest: "{{ nginx.prefix.config }}/nginx.conf"
    - src: http.d/moved_permanently.conf
      dest: "{{ nginx.prefix.config }}/http.d/moved_permanently.conf"
    - src: include/https_params.conf
      dest: "{{ nginx.prefix.config }}/include/https_params.conf"
    - src: include/letsencrypt.conf
      dest: "{{ nginx.prefix.config }}/include/letsencrypt.conf"
    - src: include/proxy_headers.conf
      dest: "{{ nginx.prefix.config }}/include/proxy_headers.conf"
    - src: include/security_headers.conf
      dest: "{{ nginx.prefix.config }}/include/security_headers.conf"
  notify: Reload nginx

- name: Template nginx default server configuration
  when: "nginx.default_server | default(True)"
  ansible.builtin.template:
    src: http.d/default.conf
    dest: "{{ nginx.prefix.config }}/http.d/default.conf"
    owner: root
    mode: "0644"
  notify: Reload nginx

- name: Create link for legacy configuration file paths
  ansible.builtin.file:
    dest: "{{ item.link }}"
    src: "{{ item.file }}"
    state: link
    force: yes
    mode: "0644"
    owner: root
  loop_control:
    label: "{{ nginx.prefix.config }}/https_params.conf dest={{ item.file }}"
  loop:
    - link: "{{ nginx.prefix.config }}/https_params.conf"
      file: "include/https_params.conf"
    - link: "{{ nginx.prefix.config }}/https"
      file: "include/https_params.conf"
    - link: "{{ nginx.prefix.config }}/security_headers"
      file: "include/security_headers.conf"
  notify: Reload nginx
