---
- name: Create nginx drop-in configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx.prefix.config }}/include"
    - "{{ nginx.prefix.config }}/http.d"
    - "{{ nginx.prefix.config }}/stream.d"

- name: Template nginx configuration
  loop:
    - src: nginx.conf
      dest: "{{ nginx.prefix.config }}/nginx.conf"
    - src: http.d/default.conf
      dest: "{{ nginx.prefix.config }}/http.d/default.conf"
    - src: http.d/moved_permanently.conf
      dest: "{{ nginx.prefix.config }}/http.d/moved_permanently.conf"
    - src: include/https_params.conf
      dest: "{{ nginx.prefix.config }}/include/https_params.conf"
    - src: include/letsencrypt.conf
      dest: "{{ nginx.prefix.config }}/include/letsencrypt.conf"
    - src: include/proxy_headers.conf
      dest: "{{ nginx.prefix.config }}/include/proxy_headers.conf"
    - src: include/security_headers.conf
      dest: "{{ nginx.prefix.config }}/include/security_headers.conf"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify: Reload nginx

- name: Create link for legacy configuration file paths
  file:
    dest: "{{ item.link }}"
    src: "{{ item.file }}"
    state: link
    force: yes
  loop_control:
    label:  "{{ nginx.prefix.config }}/https_params.conf dest={{ item.file }}"
  with_items:
    - link: "{{ nginx.prefix.config }}/https_params.conf"
      file: "include/https_params.conf"
    - link: "{{ nginx.prefix.config }}/https"
      file: "include/https_params.conf"
    - link: "{{ nginx.prefix.config }}/security_headers"
      file: "include/security_headers.conf"
  notify: Reload nginx
