---
- name: Create nginx drop-in configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx.prefix.config }}/include"
    - "{{ nginx.prefix.config }}/http.d"

- name: Template nginx configuration
  template:
    src: "{{ item }}"
    dest: "{{ render_path }}"
  loop_control:
    label: "{{ render_path }}"
  vars:
    template_dir: "{{ role_path }}/templates"
    render_path: "{{ nginx.prefix.config }}/{{ item|strip_prefix(template_dir + '/')|strip_suffix('.j2') }}"
  with_fileglob:
    - "{{ role_path }}/templates/*.j2"
    - "{{ role_path }}/templates/include/*.j2"
    - "{{ role_path }}/templates/http.d/*.j2"
  notify: Reload nginx

- name: Create link for legacy configuration file paths
  file:
    dest: "{{ item.link }}"
    src: "{{ item.file }}"
    state: link
    force: yes
  loop_control:
    label:  "{{ nginx.prefix.config }}/https_params.conf dest={{ item.file }}"
  with_items:
    - link: "{{ nginx.prefix.config }}/https_params.conf"
      file: "include/https_params.conf"
    - link: "{{ nginx.prefix.config }}/https"
      file: "include/https_params.conf"
    - link: "{{ nginx.prefix.config }}/security_headers"
      file: "include/security_headers.conf"
  notify: Reload nginx
