---
- name: Install pre-generated Diffie-Hellman parameters (RFC 3526, {{ nginx.dhparam_bits | string }})
  ansible.builtin.copy:
    src: dh-{{ nginx.dhparam_bits | string }}-rfc3526.pem
    dest: "{{ nginx.prefix.config }}/dhparam.pem"
    owner: root
    group: "{{ 'root' if ansible_os_family == 'Debian' else 'wheel' }}"
    mode: "0644"
  notify: Reload nginx
