---
- name: Generate custom DH primes (this might take up to an hour)
  command: >
    openssl dhparam -out {{ item|quote }} {{ nginx.dhparam_bits|string|quote }}
  args:
    creates: "{{ item }}"
  with_items:
    - "{{ nginx.prefix.config.general }}/dhparam.pem"
