- name: Create htpasswd files
  loop: "{{ nginx.htpasswd|nginx_htpasswd_flatten }}"
  loop_control:
    label: "{{ htpasswd_file }} username={{ item.username }}"
  vars:
    htpasswd_file: "{{ nginx.prefix.config }}/include/{{ item.htpasswd }}.htpasswd"
  htpasswd:
    path: "{{ htpasswd_file }}"
    group: www
    mode: 0640
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    crypt_scheme: "{{ item.crypt_scheme }}"
    state: "{{ 'present' if item.password else 'absent' }}"
