---
- name: Determine the nginx version
  check_mode: no
  register: nginx_version
  ansible.builtin.shell:
    executable: "{{ '/bin/bash' if ansible_system == 'Linux' else '/usr/local/bin/bash' }}"
    cmd: nginx -v 2>&1 | grep -o "[0-9]*\\.[0-9]*\\.[0-9]*"

- name: Set the http2 directive fact depending on the nginx version
  ansible.builtin.set_fact:
    nginx_separate_http2: "{{ true if nginx_version.stdout is version('1.25.1', '>=') else false }}"
