---
- name: Install nginx
  ansible.builtin.include_tasks: install.yaml

- name: Configure nginx
  ansible.builtin.include_tasks: config.yaml

- name: Generate DH Params
  ansible.builtin.include_tasks: dhparam.yaml

- name: Manage htpasswd files
  ansible.builtin.include_tasks: htpasswd.yaml

- name: Check for modsecurity support
  register: modsecurity_module
  ansible.builtin.stat:
    path: "{{ nginx.dynamic_modules_path }}/ngx_http_modsecurity_module.so"

- name: Set up Modsecurity
  ansible.builtin.include_tasks: modsecurity.yaml
  when: nginx.modsecurity.enabled and modsecurity_module.stat.exists
