---
- name: Install nginx
  ansible.builtin.include_tasks: install.yaml

- name: Set the http2 directive fact
  ansible.builtin.include_tasks: http2.yaml

- name: Configure nginx
  ansible.builtin.include_tasks: config.yaml

- name: Generate DH Params
  ansible.builtin.include_tasks: dhparam.yaml

- name: Manage htpasswd files
  ansible.builtin.include_tasks: htpasswd.yaml

- name: Set up Modsecurity on Ubuntu/Debian
  ansible.builtin.include_tasks: modsecurity-debian.yaml
  when:
    - nginx.modsecurity.enabled
    - ansible_os_family == "Debian"

- name: Check for modsecurity support
  register: modsecurity_module
  ansible.builtin.stat:
    path: "{{ nginx.dynamic_modules_path }}/ngx_http_modsecurity_module.so"

- name: Set up Modsecurity
  ansible.builtin.include_tasks: modsecurity.yaml
  when:
    - nginx.modsecurity.enabled
    - modsecurity_module.stat.exists

- name: Modify mimetypes
  ansible.builtin.include_tasks: mimetypes.yaml
  when: nginx.mimetypes is not string and nginx.mimetypes is iterable and nginx.mimetypes is mapping
