---
- name: Install nginx
  ansible.builtin.include_tasks: install.yaml

- name: Configure nginx
  ansible.builtin.include_tasks: config.yaml

- name: Generate DH Params
  ansible.builtin.include_tasks: dhparam.yaml

- name: Manage htpasswd files
  ansible.builtin.include_tasks: htpasswd.yaml
