---
- name: Converge
  hosts: all
  environment:
    GITHUB_ACTIONS: "maybe"
  tasks:
    - name: "Include ansible-proserver-nginx"
      ansible.builtin.include_role:
        name: "ansible-proserver-nginx"
